module TTY
  module Cursor
    def self.backward: (Integer n) -> String
    alias self.cursor_backward self.backward

    def self.column: (Integer n) -> String

    def self.clear_char: (?Integer? n) -> String

    def self.clear_line: () -> String

    def self.clear_line_after: () -> String

    def self.clear_line_before: () -> String

    def self.clear_lines: (Integer n, ?Symbol? direction) -> String
    alias self.clear_rows self.clear_lines

    def self.clear_screen: () -> String

    def self.clear_screen_down: () -> String

    def self.clear_screen_up: () -> String

    def self.current: () -> String

    def self.down: (Integer n) -> String
    alias self.cursor_down self.down

    def self.forward: (Integer n) -> String
    alias self.cursor_forward self.forward

    def self.move: (Integer x, Integer y) -> String

    def self.move_to: (Integer x, Integer y) -> String

    def self.next_line: () -> String

    def self.prev_line: () -> String

    def self.restore: () -> String

    def self.row: (Integer n) -> String

    def self.save: () -> String

    def self.scroll_down: () -> String

    def self.scroll_up: () -> String

    def self.up: (Integer n) -> String
    alias self.cursor_up self.up
  end
end
